FROM            ipfs/go-ipfs as ipfs

FROM            jpauwels/sonic-annotator:v1.5-ubuntu18.04
RUN             apt update && apt -y install curl python ca-certificates && rm -rf /var/lib/apt/lists/*
RUN             curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl \
 &&             chmod a+rx /usr/local/bin/youtube-dl
RUN             set -xe \
 &&             curl -k https://aubio.org/bin/vamp-aubio-plugins/0.5.1/vamp-aubio-plugins-0.5.1-x86_6