#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep "\.go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
    exit 0
fi

GOLINT=$GOPATH/bin/golint
GOIMPORTS=$GOPATH/bin/goimports
PASS=true

# Check for golint
if [[ ! -x "$GOLINT" ]]; then
    printf "\t\033[41mPlease install golint\033[