// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: sgtm.proto

/*
Package sgtmpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sgtmpb

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

func request_WebAPI_UserList_0(ctx context.Context, marshaler runtime.Marshaler, client WebAPIClient, req 