// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: sgtm.proto

/*
Package sgtmpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sgtmpb

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/go