name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Run Semantic Release
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #-
      #  name: Set up Go
      #  if: steps.semantic.outputs.new-release-published == 'true'
      #  uses: actions/setup-go@v2
      #  with:
      #    go-version: 1.15.2
      #-
      #  name: Cache Go modules
      #  if: steps.semantic.outputs.new-release-published == 'true'
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/go/pkg/mod
      #    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #    restore-keys: |
      #      ${{ runner.os }}-go-
      #-
      #  name: Run GoReleaser
      #  if: steps.semantic.outputs.new-release-published == 'true'
      #  uses: goreleaser/goreleaser-action@v2
      #  with:
      #    version: latest
      #    args: release --rm-dist
      #  env:
      #   